services:
  webapp:
    build: ./go
    environment:
      GOOGLE_CLOUD_PROJECT: triple-innocent
      GOOGLE_APPLICATION_CREDENTIALS: /home/isucon/credentials/service-account-file.json
      ISUCON_DB_HOST: isucon3
      ISUCON_DB_PORT: 3306
      ISUCON_SCORE_DB_HOST: isucon2
      ISUCON_SCORE_DB_PORT: 3306
      ISUCON_DB_USER: isucon
      ISUCON_DB_PASSWORD: isucon
      ISUCON_DB_NAME: isuports
    network_mode: host
    volumes:
      - /home/isucon/webapp/tenant_db:/home/isucon/webapp/tenant_db
      - /home/isucon/webapp/sql:/home/isucon/webapp/sql
      - /home/isucon/webapp/public.pem:/home/isucon/webapp/public.pem:ro
      - /home/isucon/initial_data:/home/isucon/initial_data
      - /home/isucon/tmp:/home/isucon/tmp
      - /home/isucon/credentials:/home/isucon/credentials
      - /home/isucon/dump:/home/isucon/dump
    init: true
